
export enum Language {
  English = 'en',
  Spanish = 'es',
  Portuguese = 'pt',
  French = 'fr',
  German = 'de',
  Polish = 'pl',
  Italian = 'it',
  Japanese = 'ja',
  Chinese = 'ch',
  Korean = 'ko',
  Dutch = 'nl',
  Turkish = 'tr',
  Swedish = 'sv',
  Indonesian = 'id',
  Filipino = 'ph',
  Ukrainian = 'uk',
  Greek = 'el',
  Czech = 'cs',
  Finnish = 'fi',
  Romanian = 'ro',
  Russian = 'ru',
  Danish = 'da',
  Bulgarian = 'bg',
  Malay = 'ms',
  Slovak = 'sk',
  Croatian = 'hr',
  Arabic = 'ar',
  Tamil = 'ta',
  Hindi = 'hi',
}

export const languageNames: Record<Language, string> = {
  [Language.English]: 'English',
  [Language.Spanish]: 'Español',
  [Language.Portuguese]: 'Português',
  [Language.French]: 'Français',
  [Language.German]: 'Deutsche',
  [Language.Polish]: 'Polskie',
  [Language.Italian]: 'Italiano',
  [Language.Japanese]: '日本語',
  [Language.Chinese]: '中文',
  [Language.Korean]: '한국어',
  [Language.Dutch]: 'Nederlands',
  [Language.Turkish]: 'Türk',
  [Language.Swedish]: 'Svenska',
  [Language.Indonesian]: 'Bahasa Indonesia',
  [Language.Filipino]: 'Pilipino',
  [Language.Ukrainian]: 'українська',
  [Language.Greek]: 'Ελληνικά',
  [Language.Czech]: 'Čeština',
  [Language.Finnish]: 'Suomalainen',
  [Language.Romanian]: 'Română',
  [Language.Russian]: 'русский',
  [Language.Danish]: 'Dansk',
  [Language.Bulgarian]: 'български',
  [Language.Malay]: 'Melayu',
  [Language.Slovak]: 'Slovenský',
  [Language.Croatian]: 'Hrvatski',
  [Language.Arabic]: 'عربى',
  [Language.Tamil]: 'தமிழ்',
  [Language.Hindi]: 'हिन्दी',
}
