import { Language } from './languages'

export const selectNativeLanguagePrompt = (lang: Language): string => {
  switch (lang) {
    case Language.English: return 'Select your native language'
    case Language.Spanish: return 'Selecciona tu idioma nativo'
    case Language.Portuguese: return 'Selecione seu idioma nativo'
    case Language.French: return 'Sélectionnez votre langue maternelle'
    case Language.German: return 'Wählen Sie Ihre Muttersprache'
    case Language.Polish: return 'Wybierz swój język ojczysty'
    case Language.Italian: return 'Seleziona la tua lingua madre'
    case Language.Japanese: return '母国語を選択'
    case Language.Chinese: return '选择您的母语'
    case Language.Korean: return '모국어를 선택'
    case Language.Dutch: return 'Selecteer uw moedertaal'
    case Language.Turkish: return 'Anadilinizi seçin'
    case Language.Swedish: return 'Välj ditt modersmål'
    case Language.Indonesian: return 'Pilih bahasa ibu Anda'
    case Language.Filipino: return 'Pumili ng iyong katutubong wika'
    case Language.Ukrainian: return 'Виберіть свою рідну мову'
    case Language.Greek: return 'Επιλέξτε τη μητρική σας γλώσσα'
    case Language.Czech: return 'Vyberte svůj mateřský jazyk'
    case Language.Finnish: return 'Valitse äidinkielesi'
    case Language.Romanian: return 'Selectați limba maternă'
    case Language.Russian: return 'Выберите свой родной язык'
    case Language.Danish: return 'Vælg dit modersmål'
    case Language.Bulgarian: return 'Изберете родния си език'
    case Language.Malay: return 'Pilih bahasa ibunda Anda'
    case Language.Slovak: return 'Vyberte svoj materinský jazyk'
    case Language.Croatian: return 'Odaberite svoj materinski jezik'
    case Language.Arabic: return 'اختر لغتك الأم'
    case Language.Tamil: return 'உங்கள் தாய்மொழியைத் தேர்ந்தெடுக்கவும்'
    case Language.Hindi: return 'अपनी मातृभाषा का चयन करें'
  }
}

export const selectForeignLanguagePrompt = (lang: Language): string => {
  switch (lang) {
    case Language.English: return 'Select the foreign language to practice'
    case Language.Spanish: return 'Selecciona el idioma extranjero para practicar'
    case Language.Portuguese: return 'Selecione o idioma estrangeiro para praticar'
    case Language.French: return 'Sélectionnez la langue étrangère à pratiquer'
    case Language.German: return 'Wählen Sie die Fremdsprache zum Üben'
    case Language.Polish: return 'Wybierz język obcy do praktyki'
    case Language.Italian: return 'Seleziona la lingua straniera da praticare'
    case Language.Japanese: return '練習する外国語を選択'
    case Language.Chinese: return '选择要练习的外语'
    case Language.Korean: return '연습할 외국어 선택'
    case Language.Dutch: return 'Selecteer de vreemde taal om te oefenen'
    case Language.Turkish: return 'Egzersiz yapmak için yabancı dili seçin'
    case Language.Swedish: return 'Välj det främmande språket att öva'
    case Language.Indonesian: return 'Pilih bahasa asing untuk berlatih'
    case Language.Filipino: return 'Pumili ng dayuhang wika na pag-aralan'
    case Language.Ukrainian: return 'Виберіть іноземну мову для вправ'
    case Language.Greek: return 'Επιλέξτε την ξένη γλώσσα για πρακτική'
    case Language.Czech: return 'Vyberte cizí jazyk k cvičení'
    case Language.Finnish: return 'Valitse vieras kieli harjoitella'
    case Language.Romanian: return 'Selectați limba străină pentru a practica'
    case Language.Russian: return 'Выберите иностранный язык для практики'
    case Language.Danish: return 'Vælg det fremmede sprog at øve'
    case Language.Bulgarian: return 'Изберете чужд език за практика'
    case Language.Malay: return 'Pilih bahasa asing untuk berlatih'
    case Language.Slovak: return 'Vyberte cudzí jazyk na cvičenie'
    case Language.Croatian: return 'Odaberite strani jezik za vježbanje'
    case Language.Arabic: return 'اختر اللغة الأجنبية للممارسة'
    case Language.Tamil: return 'பயிற்சிக்க வெளியேறும் வெற்றியைத் தேர்ந்தெடுக்கவும்'
    case Language.Hindi: return 'अभ्यास के लिए विदेशी भाषा का चयन करें'
  }
}

export const selectForeignLanguageSubPrompt = (lang: Language): string => {
  switch (lang) {
    case Language.English: return 'Get familiar with conversing in this language!'
    case Language.Spanish: return '¡Familiarízate con la conversación en este idioma!'
    case Language.Portuguese: return 'Familiarize-se com a conversa neste idioma!'
    case Language.French: return 'Familiarisez-vous avec la conversation dans cette langue!'
    case Language.German: return 'Gewöhnen Sie sich an das Gespräch in dieser Sprache!'
    case Language.Polish: return 'Zapoznaj się z rozmową w tym języku!'
    case Language.Italian: return 'Abituati a conversare in questa lingua!'
    case Language.Japanese: return 'この言語での会話に慣れる！'
    case Language.Chinese: return '熟悉这种语言的交谈！'
    case Language.Korean: return '이 언어로 대화에 익숙해지세요!'
    case Language.Dutch: return 'Maak kennis met converseren in deze taal!'
    case Language.Turkish: return 'Bu dilde konuşmaya alışın!'
    case Language.Swedish: return 'Bli bekant med att samtala på detta språk!'
    case Language.Indonesian: return 'Kenali percakapan dalam bahasa ini!'
    case Language.Filipino: return 'Maging pamilyar sa pakikipag-usap sa wika na ito!'
    case Language.Ukrainian: return 'Познайомтеся з розмовою на цій мові!'
    case Language.Greek: return 'Εξοικειωθείτε με τη συνομιλία σε αυτή τη γλώσσα!'
    case Language.Czech: return 'Seznamte se s konverzací v tomto jazyce!'
    case Language.Finnish: return 'Tutustu keskusteluun tässä kielessä!'
    case Language.Romanian: return 'Familiarizați-vă cu conversația în această limbă!'
    case Language.Russian: return 'Познакомьтесь с разговором на этом языке!'
    case Language.Danish: return 'Bliv fortrolig med at samtale på dette sprog!'
    case Language.Bulgarian: return 'Запознайте се с разговора на този език!'
    case Language.Malay: return 'Kenali perbualan dalam bahasa ini!'
    case Language.Slovak: return 'Zoznámte sa s konverzáciou v tomto jazyku!'
    case Language.Croatian: return 'Upoznajte se s razgovorom na ovom jeziku!'
    case Language.Arabic: return 'تعرف على الحديث بهذه اللغة!'
    case Language.Tamil: return 'இந்த மொழியில் உரையாடலை அறியுங்கள்!'
    case Language.Hindi: return 'इस भाषा में बातचीत के साथ परिचित हों!'
  }
}

export const typeMessagePrompt = (lang: Language): string => {
  switch (lang) {
    case Language.English: return 'Type a message...'
    case Language.Spanish: return 'Escribe un mensaje...'
    case Language.Portuguese: return 'Digite uma mensagem...'
    case Language.French: return 'Tapez un message...'
    case Language.German: return 'Geben Sie eine Nachricht ein...'
    case Language.Polish: return 'Wpisz wiadomość...'
    case Language.Italian: return 'Digita un messaggio...'
    case Language.Japanese: return 'メッセージを入力...'
    case Language.Chinese: return '输入消息...'
    case Language.Korean: return '메시지 입력...'
    case Language.Dutch: return 'Typ een bericht...'
    case Language.Turkish: return 'Bir mesaj yazın...'
    case Language.Swedish: return 'Skriv ett meddelande...'
    case Language.Indonesian: return 'Ketik pesan...'
    case Language.Filipino: return 'Magtype ng mensahe...'
    case Language.Ukrainian: return 'Введіть повідомлення...'
    case Language.Greek: return 'Πληκτρολογήστε ένα μήνυμα...'
    case Language.Czech: return 'Zadejte zprávu...'
    case Language.Finnish: return 'Kirjoita viesti...'
    case Language.Romanian: return 'Tastați un mesaj...'
    case Language.Russian: return 'Введите сообщение...'
    case Language.Danish: return 'Skriv en besked...'
    case Language.Bulgarian: return 'Въведете съобщение...'
    case Language.Malay: return 'Taipkan mesej...'
    case Language.Slovak: return 'Napíšte správu...'
    case Language.Croatian: return 'Unesite poruku...'
    case Language.Arabic: return 'اكتب رسالة...'
    case Language.Tamil: return 'ஒரு செய்தி தட்டச்சு...'
    case Language.Hindi: return 'एक संदेश टाइप करें...'
  }
}

export const chooseMissionPrompt = (lang: Language): string => {
  switch (lang) {
    case Language.English: return 'We have three missions for you to choose from. Which one would you like to start with?'
    case Language.Spanish: return 'Tenemos tres misiones para que elijas. ¿Con cuál te gustaría comenzar?'
    case Language.Portuguese: return 'Temos três missões para você escolher. Com qual você gostaria de começar?'
    case Language.French: return 'Nous avons trois missions parmi lesquelles vous pouvez choisir. Avec laquelle aimeriez-vous commencer?'
    case Language.German: return 'Wir haben drei Missionen, aus denen Sie wählen können. Mit welcher möchten Sie beginnen?'
    case Language.Polish: return 'Mamy trzy misje, z których możesz wybierać. Z którą chciałbyś zacząć?'
    case Language.Italian: return 'Abbiamo tre missioni tra cui puoi scegliere. Con quale ti piacerebbe iniziare?'
    case Language.Japanese: return '選択肢のミッションが3つあります。どれから始めますか？'
    case Language.Chinese: return '我们有三个任务供您选择。您想从哪一个开始？'
    case Language.Korean: return '선택할 수있는 세 가지 미션이 있습니다. 어떤 것부터 시작하고 싶으세요?'
    case Language.Dutch: return 'We hebben drie missies waaruit je kunt kiezen. Met welke zou je willen beginnen?'
    case Language.Turkish: return 'Seçebileceğiniz üç görevimiz var. Hangisiyle başlamak istersiniz?'
    case Language.Swedish: return 'Vi har tre uppdrag att välja mellan. Med vilken skulle du vilja börja?'
    case Language.Indonesian: return 'Kami memiliki tiga misi untuk Anda pilih. Dengan yang mana Anda ingin memulai?'
    case Language.Filipino: return 'May tatlong misyon na maaari mong piliin. Alin ang nais mong simulan?'
    case Language.Ukrainian: return 'У нас є три місії, з яких ви можете вибрати. З якою ви хочете почати?'
    case Language.Greek: return 'Έχουμε τρεις αποστολές για εσάς να επιλέξετε. Με ποιο θα θέλατε να ξεκινήσετε;'
    case Language.Czech: return 'Máme tři mise, ze kterých si můžete vybrat. S kterým byste chtěli začít?'
    case Language.Finnish: return 'Meillä on kolme tehtävää, joista voit valita. Millä haluaisit aloittaa?'
    case Language.Romanian: return 'Avem trei misiuni din care puteți alege. Cu care ați dori să începeți?'
    case Language.Russian: return 'У нас есть три миссии, из которых вы можете выбрать. С какой вы хотели бы начать?'
    case Language.Danish: return 'Vi har tre missioner, som du kan vælge imellem. Med hvilken vil du gerne begynde?'
    case Language.Bulgarian: return 'Имаме три мисии, от които можете да избирате. С коя бихте искали да започнете?'
    case Language.Malay: return 'Kami mempunyai tiga misi untuk anda pilih. Dengan yang mana anda ingin mula?'
    case Language.Slovak: return 'Máme tri misie, z ktorých si môžete vybrať. S ktorým by ste chceli začať?'
    case Language.Croatian: return 'Imamo tri misije koje možete odabrati. S kojom biste željeli započeti?'
    case Language.Arabic: return 'لدينا ثلاث مهام يمكنك اختيارها. ما الذي ترغب في البدء به؟'
    case Language.Tamil: return 'நீங்கள் தேர்ந்தெடுக்க முடியும் மூன்று பிரிவில் ஒன்றை. நீங்கள் எப்போது தொடங்க விரும்புகிறீர்கள்?'
    case Language.Hindi: return 'हमारे पास आपके लिए तीन मिशन हैं जिनमें से आपको चुनना होगा। आप किसके साथ शुरू करना चाहेंगे?'
  }
}

export const selectPrompt = (lang: Language): string => {
  switch (lang) {
    case Language.English: return 'Select'
    case Language.Spanish: return 'Seleccionar'
    case Language.Portuguese: return 'Selecione'
    case Language.French: return 'Sélectionner'
    case Language.German: return 'Wählen'
    case Language.Polish: return 'Wybierz'
    case Language.Italian: return 'Seleziona'
    case Language.Japanese: return '選択'
    case Language.Chinese: return '选择'
    case Language.Korean: return '선택'
    case Language.Dutch: return 'Selecteer'
    case Language.Turkish: return 'Seç'
    case Language.Swedish: return 'Välj'
    case Language.Indonesian: return 'Pilih'
    case Language.Filipino: return 'Pumili'
    case Language.Ukrainian: return 'Вибрати'
    case Language.Greek: return 'Επιλέξτε'
    case Language.Czech: return 'Vybrat'
    case Language.Finnish: return 'Valitse'
    case Language.Romanian: return 'Selectați'
    case Language.Russian: return 'Выбрать'
    case Language.Danish: return 'Vælg'
    case Language.Bulgarian: return 'Изберете'
    case Language.Malay: return 'Pilih'
    case Language.Slovak: return 'Vybrať'
    case Language.Croatian: return 'Odaberite'
    case Language.Arabic: return 'اختر'
    case Language.Tamil: return 'தேர்ந்தெடு'
    case Language.Hindi: return 'चुनें'
  }
}

export const foodAndDrinksPrompt = (lang: Language): string => {
  switch (lang) {
    case Language.English: return 'Food & Drinks'
    case Language.Spanish: return 'Comida y Bebidas'
    case Language.Portuguese: return 'Comida e Bebidas'
    case Language.French: return 'Nourriture et Boissons'
    case Language.German: return 'Essen und Trinken'
    case Language.Polish: return 'Jedzenie i Napoje'
    case Language.Italian: return 'Cibo e Bevande'
    case Language.Japanese: return '食べ物と飲み物'
    case Language.Chinese: return '食品和饮料'
    case Language.Korean: return '음식과 음료'
    case Language.Dutch: return 'Eten en Drinken'
    case Language.Turkish: return 'Yiyecek ve İçecek'
    case Language.Swedish: return 'Mat och Dryck'
    case Language.Indonesian: return 'Makanan & Minuman'
    case Language.Filipino: return 'Pagkain at Inumin'
    case Language.Ukrainian: return 'Їжа та напої'
    case Language.Greek: return 'Φαγητό και ποτά'
    case Language.Czech: return 'Jídlo a Nápoje'
    case Language.Finnish: return 'Ruoka ja Juomat'
    case Language.Romanian: return 'Mâncare și Băuturi'
    case Language.Russian: return 'Еда и напитки'
    case Language.Danish: return 'Mad og Drikke'
    case Language.Bulgarian: return 'Храна и Напитки'
    case Language.Malay: return 'Makanan & Minuman'
    case Language.Slovak: return 'Jedlo a Nápoje'
    case Language.Croatian: return 'Hrana i Piće'
    case Language.Arabic: return 'طعام وشراب'
    case Language.Tamil: return 'உணவு & பானங்கள்'
    case Language.Hindi: return 'खाना और पेय'
  }
}

export const schoolLifePrompt = (lang: Language): string => {
  switch (lang) {
    case Language.English: return 'School Life'
    case Language.Spanish: return 'Vida Escolar'
    case Language.Portuguese: return 'Vida Escolar'
    case Language.French: return 'Vie Scolaire'
    case Language.German: return 'Schulleben'
    case Language.Polish: return 'Życie Szkolne'
    case Language.Italian: return 'Vita Scolastica'
    case Language.Japanese: return '学校生活'
    case Language.Chinese: return '校园生活'
    case Language.Korean: return '학교 생활'
    case Language.Dutch: return 'Schoolleven'
    case Language.Turkish: return 'Okul Hayatı'
    case Language.Swedish: return 'Skol Liv'
    case Language.Indonesian: return 'Kehidupan Sekolah'
    case Language.Filipino: return 'Buhay Eskwela'
    case Language.Ukrainian: return 'Шкільне Життя'
    case Language.Greek: return 'Σχολική Ζωή'
    case Language.Czech: return 'Školní Život'
    case Language.Finnish: return 'Kouluelämä'
    case Language.Romanian: return 'Viața Școlară'
    case Language.Russian: return 'Школьная Жизнь'
    case Language.Danish: return 'Skoleliv'
    case Language.Bulgarian: return 'Училищен Живот'
    case Language.Malay: return 'Hidup Sekolah'
    case Language.Slovak: return 'Školský Život'
    case Language.Croatian: return 'Školski Život'
    case Language.Arabic: return 'حياة المدرسة'
    case Language.Tamil: return 'பள்ளி வாழ்க்கை'
    case Language.Hindi: return 'स्कूल जीवन'
  }
}

export const familyTimePrompt = (lang: Language): string => {
  switch (lang) {
    case Language.English: return 'Family Time'
    case Language.Spanish: return 'Tiempo en Familia'
    case Language.Portuguese: return 'Tempo em Família'
    case Language.French: return 'Temps en Famille'
    case Language.German: return 'Familienzeit'
    case Language.Polish: return 'Czas Rodzinny'
    case Language.Italian: return 'Tempo in Famiglia'
    case Language.Japanese: return '家族の時間'
    case Language.Chinese: return '家庭时间'
    case Language.Korean: return '가족 시간'
    case Language.Dutch: return 'Familietijd'
    case Language.Turkish: return 'Aile Zamanı'
    case Language.Swedish: return 'Familjetid'
    case Language.Indonesian: return 'Waktu Keluarga'
    case Language.Filipino: return 'Oras ng Pamilya'
    case Language.Ukrainian: return 'Час з сім’єю'
    case Language.Greek: return 'Οικογενειακός Χρόνος'
    case Language.Czech: return 'Rodinný Čas'
    case Language.Finnish: return 'Perheaika'
    case Language.Romanian: return 'Timpul în Familie'
    case Language.Russian: return 'Семейное Время'
    case Language.Danish: return 'Familietid'
    case Language.Bulgarian: return 'Семейно Време'
    case Language.Malay: return 'Masa Keluarga'
    case Language.Slovak: return 'Rodinný Čas'
    case Language.Croatian: return 'Vrijeme s Obitelji'
    case Language.Arabic: return 'وقت العائلة'
    case Language.Tamil: return 'குடும்ப நேரம்'
    case Language.Hindi: return 'परिवार समय'
  }
}
